name: Twitter Bot Auto Post - Binar

on:
  schedule:
    # Jalan tiap 2 jam sekali (WIB)
    - cron: "10 */2 * * *"
    # Job dummy tiap 6 jam biar repo nggak tidur
    - cron: "0 */6 * * *"
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone to Asia/Jakarta
        run: sudo timedatectl set-timezone Asia/Jakarta

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tweet bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: node index.js

      - name: Keep workflow alive (dummy)
        run: echo "💤 Keeping bot active at $(date)"
